services:
  supabasetubesync:
    build: .
    container_name: supabasetubesync   
    restart: no
    environment:
      API_TOKEN: ${API_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      TUBE_API_URL:  ${TUBE_API_URL}
